# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-22 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whayp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 19, 25, 24, 475751)),
        ),
    ]
