# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whayp', '0002_auto_20161218_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='07:33:00'),
        ),
    ]
