# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whayp', '0003_auto_20161219_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 23, 22, 34, 1476)),
        ),
    ]
