# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whayp', '0003_auto_20161218_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='18/12/201607:35:41'),
        ),
    ]
