# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whayp', '0004_auto_20161218_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='2016-12-18 19:38'),
        ),
    ]
